### ISSUE TITLE
Puma plugin

### ISSUE THREAD

**Issue by manuelmeurer** [hschne/puny-monitor#2]
Puny looks great! :)

Would it be possible to run it as a [Puma plugin](https://github.com/puma/puma/blob/master/docs/plugins.md) and mount the engine to a route, similar to what [Mission Control Jobs](https://github.com/rails/mission_control-jobs) does?
I'd be happy to tabe a stab at a PR with some guidance.

**Comment by hschne** [comment]
Thank you! You're always welcome to submit PRs :grin: 

I took a quick look at Mission Control Jobs. AFAIK that is a Rails Engine - which would be a bit out of scope for Puny Monitor. I deliberately used Sinatra to keep things lean and mean, ya know. But maybe I got it wrong, I'm not familiar with Puma plugins :thinking: 

That being said, I'd love to know more about your use case! Specifically, I'd be curious why the existing distribution methods (Docker, Gem) don't work for you? :)

**Comment by manuelmeurer** [comment]
I don't use Kamal or Docker, but I deploy via [Hatchbox](https://hatchbox.io/) instead.
It would be great to be able to add Puny Monitor as a gem to my Rails app, deploy and see the stats at myapp.com/stats (or any other route I choose).
I think it should be possible to mount a Sinatra app to a Rails route: https://jacobbednarz.com/posts/sinatra-in-rails (10+ years old, but maybe it still works 😄)

The Puma plugin was just an idea to start and stop the executable automatically.
But I could also start it on Hatchbox as a separate process I guess.

**Comment by hschne** [comment]
Right! So Puny Monitor is intended to be run via Docker or separate process by design. My main issue with tying monitoring server resources to Rails is that if your Rails process dies so does your monitoring. 

So I'd rather keep Puny Monitor strictly separate from Rails. For your use case, maybe this gem is of interest? 

It does exactly what Puny Monitor does, but is mounted as Rails engine 🙂

https://github.com/kobaltz/mission_control-servers

**Comment by manuelmeurer** [comment]
Thanks, I'll have a look at Mission Control Servers!
